Fix logging strings that receive multiple params
Logging functions only receives a message, and `args` that are
interpolated into that message. Current implementation was failing
because it was trying to interpolate `str(e)` to a message that doesn't
include placeholders for it.

Moved from `.format` to `%`, as that's what `logging` uses for the
interpolation.

After the fix:
```
2017-07-26 22:23:58  WARNING   Unable to load `es` language, using default `english`: [Errno 2] No translation file found for domain: u'core'
```

Relevant stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file init.py, line 240
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/handlers.py", line 845, in emit
    msg = self.format(record) + '\000'
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
```