change atexit decorator to method
the decorator points to the class method. when used during initialisation it points to the method of the object and passes self as argument.

before you might have gotten this error:
Error in atexit._run_exitfuncs:
TypeError: exit() missing 1 required positional argument: 'self'

also removed self.config.close() as ConfigParser does not have a close method