Use parser slot in ConfigOption and ConfigSection
By using a private attribute `__parser` instead of the defined slot
`parser`, the underlying MutableMapping was mapping the parser object,
getting a maximum recursion depth error, because it was trying to expand
not only the config sections and options, but also the parser itself,
over and over again.

By using the provided `parser` slot, this no longer occurs.

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "build/bdist.linux-x86_64/egg/pyload/core/init.py", line 457, in run
    self._init_config()
  File "build/bdist.linux-x86_64/egg/pyload/core/init.py", line 327, in _init_config
    session = ConfigParser(self.__SESSIONFILENAME, session_defaults)
  File "build/bdist.linux-x86_64/egg/pyload/config/parser.py", line 170, in set
    item.set(arg, *args, **kwargs)
  File "build/bdist.linux-x86_64/egg/pyload/config/parser.py", line 170, in set
    item.set(arg, *args, **kwargs)
  File "build/bdist.linux-x86_64/egg/pyload/config/parser.py", line 118, in set
    self.__parser.store()
  File "build/bdist.linux-x86_64/egg/pyload/config/parser.py", line 358, in store
    config = self._gen_fileconfig()
  File "build/bdist.linux-x86_64/egg/pyload/config/parser.py", line 350, in _gen_fileconfig
    fc = self._to_fileconfig(item, name)
  File "build/bdist.linux-x86_64/egg/pyload/config/parser.py", line 339, in _to_fileconfig
    fc = self._to_fileconfig(item, sub_name)
  File "build/bdist.linux-x86_64/egg/pyload/config/parser.py", line 335, in _to_fileconfig
    for name, item in section.loweritems():
  File "build/bdist.linux-x86_64/egg/pyload/utils/struct/init.py", line 58, in <genexpr>
    for lowerkey, (key, val) in self.__dict__.items())
  File "build/bdist.linux-x86_64/egg/pyload/utils/struct/init.py", line 36, in <genexpr>
    return iter(key for key, val in self.__dict__.values())
  File "build/bdist.linux-x86_64/egg/pyload/utils/struct/init.py", line 36, in <genexpr>
    return iter(key for key, val in self.__dict__.values())
(...)
  File "build/bdist.linux-x86_64/egg/pyload/utils/struct/init.py", line 36, in <genexpr>
    return iter(key for key, val in self.__dict__.values())
RuntimeError: maximum recursion depth exceeded
```