Fix IRCInterface and XMPPInterface
Following Error came up when I tried setting up either IRCInterface or XMPPInterface. 

AttributeError: 'IRCInterface' object has no attribute 'set_daemon'

With my change now it works. Might have been caused by the removal of chamelCase.