Rename missing function get_account_infos
`AccountManager` does not have a `get_account_infos` method. It seems
the correct one to call is `load_accounts` instead.

Relevant error:
```
CRITICAL  'AccountManager' object has no attribute 'get_account_infos'
```