Add unit to size values in config defaults
These values are expected to be strings, so regex can be applied to
them:
https://github.com/pyload/utils/blob/9b447a4de35be5011ddafaf14041b051d362b178/src/pyload/utils/parse.py#L114

Also, it is expected to have its corresponding unit, otherwise they are treated
as Bytes:
https://github.com/pyload/utils/blob/9b447a4de35be5011ddafaf14041b051d362b178/src/pyload/utils/parse.py#L119

Related stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "build/bdist.linux-x86_64/egg/pyload/core/init.py", line 461, in run
    self._init_config()
  File "build/bdist.linux-x86_64/egg/pyload/core/init.py", line 328, in _init_config
    session = ConfigParser(self.__SESSIONFILENAME, session_defaults)
  File "build/bdist.linux-x86_64/egg/pyload/config/parser.py", line 247, in __init__
    ConfigSection.__init__(self, self, config)
  File "build/bdist.linux-x86_64/egg/pyload/config/parser.py", line 140, in __init__
    self.update(config or ())
  File "build/bdist.linux-x86_64/egg/pyload/config/parser.py", line 162, in update
    for name, value in iterable
  File "build/bdist.linux-x86_64/egg/pyload/config/parser.py", line 149, in _to_configentry
    entry_obj = func(self.parser, *entry_args)
  File "build/bdist.linux-x86_64/egg/pyload/config/parser.py", line 140, in __init__
    self.update(config or ())
  File "build/bdist.linux-x86_64/egg/pyload/config/parser.py", line 162, in update
    for name, value in iterable
  File "build/bdist.linux-x86_64/egg/pyload/config/parser.py", line 149, in _to_configentry
    entry_obj = func(self.parser, *entry_args)
  File "build/bdist.linux-x86_64/egg/pyload/config/parser.py", line 73, in __init__
    self._set_value(value)
  File "build/bdist.linux-x86_64/egg/pyload/config/parser.py", line 89, in _set_value
    self.value = self.default = self._normalize_value(value)
  File "build/bdist.linux-x86_64/egg/pyload/config/parser.py", line 103, in _normalize_value
    return self._convert_map[self.type](value)
  File "build/bdist.linux-x86_64/egg/pyload/config/parser.py", line 51, in <lambda>
    InputType.Size: lambda x: 0 if x is None else parse.bytesize(x),
  File "build/bdist.linux-x86_64/egg/pyload/utils/parse.py", line 114, in bytesize
    m = _RE_SIZE.match(text)
TypeError: expected string or buffer
```