Fix inexistent attribute 'command' in CLI execution
`vars()` returns the internal dict for `args`:

```
(Pdb) print id(args.__dict__)
139935486325936
(Pdb) print id(vars(args))
139935486325936
```

Because of this, the next line doing a `pop` over it actually removes
the `command` attribute, which is referenced some lines after it, and
it's not found.

Relevant stacktrace:
```
Traceback (most recent call last):
  File "$HOME/.virtualenvs/pyload2/bin/pyload", line 11, in <module>
    load_entry_point('pyload.core==0.6.2', 'console_scripts', 'pyload')()
  File "build/bdist.linux-x86_64/egg/pyload/core/cli.py", line 159, in main
AttributeError: 'Namespace' object has no attribute 'command'
```