Change some relative imports to absolute paths
Some relative imports are failing because of the `__init__` imports done in
some modules, which make inner modules to mess up when trying to import
from parent directories. For example:

```
Traceback (most recent call last):
  File "/home/mike/.virtualenvs/pyload2/bin/pyload", line 11, in <module>
    load_entry_point('pyload.core==0.6.2', 'console_scripts', 'pyload')()
  File "/home/mike/.virtualenvs/pyload2/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 563, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/mike/.virtualenvs/pyload2/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2651, in load_entry_point
    return ep.load()
  File "/home/mike/.virtualenvs/pyload2/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2305, in load
    return self.resolve()
  File "/home/mike/.virtualenvs/pyload2/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2311, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/pyload/core/__init__.py", line 39, in <module>
  File "build/bdist.linux-x86_64/egg/pyload/core/manager/__init__.py", line 4, in <module>
  File "build/bdist.linux-x86_64/egg/pyload/core/manager/plugin.py", line 16, in <module>
ImportError: No module named network.loader
```

Changed some (not all) relative imports to absolute. It shouldn't be a
problem (how many times do we move these packages anyway?), and it's
also consistent with the imports from the rest of pyload separate
repositories.