Fix pyload 'version' command
This change fixes the `pyload version` CLI command. Because the command
functions are treated in a generic way (see
https://github.com/pyload/pyload/blob/3323fc51fa2024455728e4a0e85413917641fe0c/src/pyload/core/cli.py#L156),
it was failing because of unexpected parameters.

Relevant stacktrace:
```
Traceback (most recent call last):
  File "$HOME/.virtualenvs/pyload2/bin/pyload", line 11, in <module>
    load_entry_point('pyload.core==0.6.2', 'console_scripts', 'pyload')()
  File "build/bdist.linux-x86_64/egg/pyload/core/cli.py", line 156, in main
TypeError: version() takes no arguments (6 given)
```