Fixing "has no attribute" error
```
Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 363, in run
    self.active.plugin.preprocessing(self)
  File "/usr/share/pyload/module/plugins/internal/Base.py", line 218, in preprocessing
    return self._process(*args, **kwargs)
  File "/usr/share/pyload/module/plugins/internal/Hoster.py", line 78, in _process
    self._setup()
  File "/usr/share/pyload/module/plugins/crypter/XFileSharingProFolder.py", line 41, in _setup
    account_name     = self.classname if self.account.PLUGIN_DOMAIN is None else self.PLUGIN_NAME
AttributeError: 'NoneType' object has no attribute 'PLUGIN_DOMAIN'
```